---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  tags:
    - user

 - name: Allow 'wheel' group to have sudo previlegies
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'

- name: Create user group
  group:
    name: '{{ user.group }}'
    state: present
  tags:
    - user

- name: Create user and assign to group
  user:
    name: '{{ user.name }}'
    group: '{{ user.group }}'
    password: "{{ user_password|password_hash('sha512') }}"
    shell: '{{ user.shell }}'
    update_password: on_create
    uid: '{{ user.uid }}'
    groups: wheel
    append: yes
  tags:
    - user
