---
- name: Clone dotfiles repo
  git:
    repo: https://github.com/overtune/dotfiles.git
    dest: $HOME/.dotfiles
    bare: yes
  become_user: johrun

- name: Checks out the config files to home dir. 
  command: alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' && config checkout 
  args:
    creates: $HOME/.vimrc
  become_user: johrun
