---
- name: Clone dotfiles repo
  git:
    repo: https://github.com/overtune/dotfiles.git
    dest: $HOME/.dotfiles
    bare: yes
  become_user: johrun

- name: Installs oh-my-zsh. 
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: $HOME/.oh-my-zsh
  become_user: johrun

- name: Checks out the config files to home dir. 
  command: /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout 
  args:
    creates: $HOME/.vimrc
  become_user: johrun
