---
- name: Install Vim
  pacman:
    name:
      - vim
    state: present

- name: Install Git
  pacman:
    name:
      - git
    state: present

- name: Install Git
  pacman:
    name:
      - terminator
    state: present
