---
- name: Install vim
  pacman:
    name:
      - vim
    state: present

- name: Install git
  pacman:
    name:
      - git
    state: present

- name: Install zsh
  pacman:
    name:
      - zsh
    state: present

- name: Install tmux
  pacman:
    name:
      - tmux
    state: present

- name: Install feh
  pacman:
    name:
      - feh
    state: present

- name: Install openssh
  pacman:
    name:
      - openssh
    state: present

- name: Install mosh
  pacman:
    name:
      - mosh
    state: present

- name: Install wget
  pacman:
    name:
      - wget
    state: present

- name: Install python3
  pacman:
    name:
      - python3
    state: present

- name: Install unzip
  pacman:
    name:
      - unzip
    state: present

- name: Install fzf
  pacman:
    name:
      - fzf
    state: present

- name: Install htop
  pacman:
    name:
      - htop
    state: present
