---
- name: Install virtualbox guest additions 
  pacman:
    name:
      - virtualbox-guest-modules-arch
    state: present
  when: ansible_facts['ansible_virtualization_type'] == "virtualbox"

- name: Install xf86-video-vmware 
  pacman:
    name:
      - xf86-video-vmware 
    state: present
  when: ansible_facts['ansible_virtualization_type'] == "virtualbox"
